 development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myinsta_development
  pool: 5
  username: rails
  password: <%= ENV["DATABASE_PASS"] %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myinsta_test
  pool: 5
  username: rails
  password: <%= ENV["DATABASE_PASS"] %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myinsta_production
  pool: 5
  username: rails
  password: <%= ENV["DATABASE_PASS"] %>
  host: localhost
